assetDir = "transient/assets/"
baseURL = "https://sransara.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
title = "sransara"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[permalinks]
  notes = "/:sections/:title/"

[markup.asciidocExt]
    extensions = ["asciidoctor-diagram", "asciidoctor-bibtex"]
    workingFolderCurrent = true
    safeMode = "unsafe"
    sectionNumbers = false
    preserveTOC = true
    
    [markup.asciidocExt.attributes]
      xrefstyle = "short"
      listing-caption = "Listing"
      sectanchors = ""
      idprefix = "id:"
      idseparator = "-"
      source-highlighter = "rouge"
      icons = "font"
      stem = "latexmath"
      toc = "macro"